// Mocks generated by Mockito 5.4.6 from annotations
// in vetconnect_app/test/domain/usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vetconnect_app/data/dtos/pagina_dto.dart' as _i2;
import 'package:vetconnect_app/domain/entities/servicio.dart' as _i5;
import 'package:vetconnect_app/domain/repositories/i_servicio_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginaDto_0<T> extends _i1.SmartFake implements _i2.PaginaDto<T> {
  _FakePaginaDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IServicioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIServicioRepository extends _i1.Mock
    implements _i3.IServicioRepository {
  MockIServicioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginaDto<_i5.Servicio>> obtenerServicios({
    int? pagina = 1,
    String? busqueda = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#obtenerServicios, [], {
              #pagina: pagina,
              #busqueda: busqueda,
            }),
            returnValue: _i4.Future<_i2.PaginaDto<_i5.Servicio>>.value(
              _FakePaginaDto_0<_i5.Servicio>(
                this,
                Invocation.method(#obtenerServicios, [], {
                  #pagina: pagina,
                  #busqueda: busqueda,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.PaginaDto<_i5.Servicio>>);
}
